spring.application.name=backend
server.port=8080

app.frontend-origins=${FRONTEND_ORIGINS:http://localhost:4200,http://localhost,capacitor://localhost,http://192.168.1.103:4200}
app.ml-service-base-url=${ML_SERVICE_BASE_URL:http://localhost:8000}
app.denmark-center-lat=56.2639
app.denmark-center-lng=9.5018
app.country-code=dk
